[qdrant]
url = "https://8294e264-e739-44ca-ab59-0aff628d5f01.us-east-1-0.aws.cloud.qdrant.io:6333"
api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwiZXhwIjoxNzcyNjY0MTY1fQ.D6P0Uh4asPS0CPFvl53iEVvxw9bBneRy-wI6yvwF2NY"
